### ISSUE TITLE
Différence entre Kinect for Windows et Kinect XBox

### ISSUE THREAD

**Issue by PocketTrout** [PocketTrout/xvision#10]

**Comment by ms-studio** [comment]
Selon Microsoft: 

> With the adapter, all Kinect v2 sensors—Kinect for Windows v2 and Kinect for Xbox One—perform identically.

http://blogs.microsoft.com/blog/2014/10/22/microsoft-releases-kinect-sdk-2-0-new-adapter-kit/

Microsoft Kinect 2.0 inkl. Adapter für Windows 8, chez Digitec: 
https://www.digitec.ch/de/s1/product/microsoft-kinect-20-inkl-adapter-fuer-windows-8-schwarz-spielsteuerung-3231798
