### ISSUE TITLE
lancer quelques projets d'examples et tester la kinect

### ISSUE THREAD

**Issue by PocketTrout** [PocketTrout/xvision#2]

**Comment by PocketTrout** [comment]
Il semblerait qu'il y ait un problème de configuration avec le portable Asus que j'utilise. Bien qu'il soit équipé de ports USB 3.0 le logiciel qui vérifie les configurations hardware fourni avec le SDK Microsoft ne détecte aucun port compatible.

Il s'agirait d'une question de débit et cela se rapport à la connectique des ports USB avec la carte mère (bus PCI, etc), à vérifier...

**Comment by PocketTrout** [comment]
Le problème venait bel et biens des ports USB, la bande passant était insuffisante. Les Asus de l'école sont équipés d'un chipset ASMedia connus pour causer des problèmes avec la Kinect V2.

Avec le pc protable que le service informatique de l'école m'a prêté tout est ok.

**Comment by ms-studio** [comment]
Bien, bon à savoir!
