### ISSUE TITLE
Mode Replay

### ISSUE THREAD

**Issue by ms-studio** [PocketTrout/xvision#20]
Message de Kilian du 15 juin: 

> J'arrive enfin à relire les dernières séquences enregistrées par le dispositif, ça donne plutôt bien et j'ai même fait un mode qui les lit à l'endroit puis à l'envers en boucle pour rigoler.

> Je pensais maintenant ajouter un timer pour que le replay commence seulement après x secondes une fois qu'il n'y a plus personne.

> Comment est-ce que tu voyais la chose précisément ? Je vais continuer le développement ce week-end en laissant le plus de paramètres possible à choix mais si tu as des idées précises concernant ces replay de séquence je préférerais les connaître au plus tôt.

**Comment by ms-studio** [comment]
Voici mes réflexions sur le mode "replay":

1) Ce mode doit se déclencher après une période d'inactivité. Je commencerais par tester un délai assez court, disons 10 secondes. 

2) Si on a plusieurs séquences "replay", on fait apparaître les avatars l'un après l'autre, avec un délai de 3 secondes p.ex. 

3) Avoir plusieurs séquences replay serait bien, mais je pense qu'on peut limiter leur nombre, p.ex. à trois. Quel est actuellement le nombre maximum de détections simultanées?

4) Si une interaction est détectée, les avatars "replay" vont disparaître l'un après l'autre, également avec un delai.

6) Un bonus serait d'accompagner l'apparition / disparition d'un petit effet "flicker", quelque chose comme ça: 
Visible pendant 0.5 milisecondes / caché 0.2 ms / visible 0.2 ms / caché 0.2 ms / visible.
Cela pour imiter l'effet de qqch qui s'allume / s'éteint (pense à un tube néon).

7) Visuellement, je propose de donner aux avatars en "replay" une opacité moindre, disons 60%. Si ce réglage n'est pas appliquable, on leur donnera une couleur plus sombre pour obtenir cet effet.

Gamme de couleurs à essayer:
- Fond : noir.
- Squelette: Color32(58, 166, 111, 255) et Color32(46, 134, 99, 255) (avec un shader permettant deux teintes)
- Pour les avatars replay, mettre l'alpha à 150.

8) Un autre bonus: à chaque fois qu'une personne est détectée par la caméra, produire un effet "négatif" de l'image, en faisant une inversion des couleurs pendant une fraction de seconde,
- le fond de la scène passe du noir au vert  - Color32(58, 166, 111, 255)
- la couleur des avatars passe au noir

**Comment by PocketTrout** [comment]
Terminé avec effets négatifs et flickr
